apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  startup.sh: |
    #!/bin/sh
    echo "Pod Name: $(hostname)" > /usr/share/nginx/html/index.html
    echo "Revision: ${ARGOCD_APP_REVISION}" >> /usr/share/nginx/html/index.html
    nginx -g 'daemon off;'
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.3
        env:
        - name: ARGOCD_APP_REVISION
          value: "#{ARGOCD_APP_REVISION}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /startup.sh
          subPath: startup.sh
        command: ["/bin/sh", "/startup.sh"]
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause:
          duration: "30s"
      - setWeight: 50
      - pause:
          duration: "30s"
      - setWeight: 100
      - pause:
          duration: "10m"
